[tool.poetry]
name = "pydra-brainstat"
version = "0.0.1"
description = "Pydra tasks for BrainStat"
authors = ["Ghislain Vaillant <ghislain.vaillant@icm-institute.org>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
pydra = "^0.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
